version: '3.5'
services:
  spamass-relay:
    build: .
    container_name: spamass-relay
    ports:
      - "10025:25"
    environment:
      - RELAY_HOST=[127.0.0.1]:11025
      - SAHOME=/var/log/spamassassin/
    tty: true